default:
  options:
    retroarch.audio_latency: 64
n64:
  emulator: mupen64plus
  core:     gliden64
  options:
    videomode: DMT 4 HDMI
n64dd:
  emulator: mupen64plus
  core:     gliden64
  options:
    videomode: DMT 4 HDMI
psp:
  options:
    frameskip: automatic
    videomode: DMT 4 HDMI
gba:
  options:
    videomode: DMT 4 HDMI
    retroarch.audio_latency: 128
